gha: rerun workflow after AWS creds injected
in the circleCI pipeline it does not run until makefile sets up webhooks
but in GHA it runs as soon as zero create pushes the repo, during that
time it has no AWS credentials, so it will always fail

diff --git a/templates/.github/workflows/ci.yml b/templates/.github/workflows/ci.yml
--- a/templates/.github/workflows/ci.yml
+++ b/templates/.github/workflows/ci.yml
@@ -34,12 +34,18 @@ jobs:
   build:
       needs: unit-test
       runs-on: ubuntu-latest
+      env:
+        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       steps:
         - uses: actions/checkout@v2
         - name: Set IMAGE_TAG as env
           run: |
             IMAGE_TAG=$(git rev-parse --short=7 ${{ github.sha }})
             echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
+        - if: env.AWS_ACCESS_KEY_ID == null
+          run: |
+            echo "AWS Credentials not found, This is expected for the first run as the repo is provisioned then secrets are injected at a later step."
+            exit 1
         - name: Configure AWS credentials
           uses: aws-actions/configure-aws-credentials@v1
           with:
